GymWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path('workout/', include("workout.urls")),
    path('memberships/', include("memberships.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path

from workout.urls import app_name
from . import views

app_name='core'

urlpatterns = [
    path('', views.home, name='home'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("my_profile/", views.current_profile, name="current_profile"),
    path("logout/", views.logout_user, name="logout"),
    path("add_visit/<int:user_id>/", views.add_visit, name="add_visit"),
    path("coaches/", views.show_coaches, name="coaches"),
    path("coaches/<int:coach_id>", views.coach_info, name="coach_info"), ## dodaj imie i nazwisko w linku
    path("edit/", views.edit_info, name="edit"),
]

workout/urls.py
from django.urls import path
from . import views

app_name = 'workout'

urlpatterns = [
    path('add/', views.add_workout, name='add_workout'),
    path('schedule/', views.schedule, name='schedule'),
    path('join/', views.join_workout, name='join_workout'),
    path('leave/', views.leave_workout, name='leave_workout'),
    path('delete/', views.delete_workout, name='delete_workout'),
    path('edit/', views.edit_workout, name='edit_workout'),
    path('details/<int:workout_id>', views.details_workout, name='details_workout'),
    path('remove_from_workout/',  views.remove_client_from_workout, name='remove_client'),
]

workout/models.py
from django.db import models
from users.models import Coach, Client, User

class Workout(models.Model):
    name = models.CharField(max_length=100)
    coach = models.ForeignKey(User, on_delete=models.CASCADE, related_name='coach_workouts')
    client = models.ManyToManyField(User, related_name='client_workouts')
    description = models.TextField()
    target = models.CharField(max_length=50)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    max_participants = models.IntegerField()

    class Difficulty(models.TextChoices):
        BEGINNER = 'beginner', 'Beginner'
        INTERMEDIATE = 'intermediate', 'Intermediate'
        ADVANCED = 'advanced', 'Advanced'

    difficulty = models.CharField(
        max_length=20,
        choices=Difficulty.choices,
        null=True,
    )

    class Weekdays(models.TextChoices):
        MONDAY = 'monday', 'Monday'
        TUESDAY = 'tuesday', 'Tuesday'
        WEDNESDAY = 'wednesday', 'Wednesday'
        THURSDAY = 'thursday', 'Thursday'
        FRIDAY = 'friday', 'Friday'
        SATURDAY = 'saturday', 'Saturday'
        SUNDAY = 'sunday', 'Sunday'

    day = models.CharField(
        choices=Weekdays.choices,
        max_length=10,
        null=True,
    )

    class Status(models.TextChoices):
        ACTIVE = 'active', 'Active'
        INACTIVE = 'inactive', 'Inactive'

    status = models.CharField(
        choices=Status.choices,
        default=Status.ACTIVE,
        max_length=10,
    )

workout/forms.py
from django import forms
from datetime import time, timedelta
from utils import delete_null_choice
from workout.models import Workout

class AddWorkoutForm(forms.ModelForm):
    class Meta:
        model = Workout
        exclude = ('user', 'coach', 'status', 'client')
        widgets = {
            'difficulty': forms.Select(attrs={'class': 'form-control'}),
            'day' : forms.Select(attrs={'class': 'form-control'}),
            'start_time': forms.TimeInput(attrs={'class': 'form-control',
                                                 'type': 'time'}),
            'end_time': forms.TimeInput(attrs={'class': 'form-control',
                                                 'type': 'time'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['difficulty'].choices = delete_null_choice(self.fields['difficulty'].choices)
        self.fields['day'].choices = delete_null_choice(self.fields['day'].choices)

    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get('start_time')
        end_time = cleaned_data.get('end_time')
        day = cleaned_data.get('day')

        workouts = Workout.objects.filter(day=day)
        for workout in workouts:
            if (workout.start_time <= start_time < workout.end_time
                or workout.start_time < end_time < workout.end_time
            or start_time < time(6,0)
            or end_time > time(22, 0)
            or start_time == end_time
            or (end_time.hour - start_time.hour) > 1):
                raise forms.ValidationError("This time is not available")

        return cleaned_data

workout/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from users.models import User
from workout.forms import AddWorkoutForm
from workout.models import Workout


def is_coach(user):
    return user.is_coach

@login_required
@user_passes_test(is_coach, login_url='/')
def add_workout(request):
    context = {
        'title': 'Add Workout',
    }
    form = AddWorkoutForm()
    if request.method == "POST":
        form = AddWorkoutForm(request.POST)
        if form.is_valid():
            workout = form.save(commit=False)
            workout.coach = request.user
            workout.save()
            return redirect("users:current_profile")
    context["form"] = form
    return render(request, "users/form.html", context)

def schedule(request):
    context = {
        'workouts': Workout.objects.all().filter(status='active').order_by('start_time').values(),
        'weekdays': Workout.Weekdays.choices
    }
    return render(request, "workout/schedule.html", context)

@login_required
def join_workout(request):
    if request.user.client_workouts.count == 1 and request.user.client.membership != 'premium':
        return redirect("workout:schedule")
    workout_id = request.GET.get('workout_id')
    workout = Workout.objects.get(id=workout_id)
    clients_count = workout.client.all().count()
    if workout.max_participants > clients_count:
        workout.client.add(request.user)
    return redirect("workout:schedule")

@login_required
def leave_workout(request):
    workout_id = request.GET.get('workout_id')
    try:
        workout = Workout.objects.get(id=workout_id)
        workout.client.remove(request.user)
        return redirect("users:current_profile")
    except Workout.DoesNotExist:
        return HttpResponse('no such workout')

@login_required
@user_passes_test(is_coach, login_url='/')
def delete_workout(request):
    workout_id = request.GET.get('workout_id')
    try:
        workout = Workout.objects.get(id=workout_id)
        if workout.coach == request.user:
            workout.client.clear()
            workout.status = 'inactive'
            workout.save()
        return redirect('users:current_profile')
    except Workout.DoesNotExist:
        return HttpResponse('no such workout')

@login_required
@user_passes_test(is_coach, login_url='/')
def edit_workout(request):
    workout_id = request.GET.get('workout_id')
    workout = Workout.objects.get(id=workout_id)
    if request.user != workout.coach:
        return redirect("users:current_profile")
    context = {
        'title': 'edit workout',
    }
    if workout.coach != request.user:
        return HttpResponse('not authorized')
    if request.method == "POST":
        form = AddWorkoutForm(request.POST, instance=workout)
        form.save()
        return redirect("users:current_profile")
    context['form'] = AddWorkoutForm(instance=workout)
    return render(request, "users/form.html", context)

def details_workout(request, workout_id):
    try:
        workout = Workout.objects.get(id=workout_id)
        context = {
            'workout': workout,
        }
        return render(request, "workout/details.html", context)
    except Workout.DoesNotExist:
        return HttpResponse('no such workout')

@login_required
@user_passes_test(is_coach, login_url='/')
def remove_client_from_workout(request):
    workout_id = request.GET.get('workout_id')
    client_id = request.GET.get('client_id')
    workout = Workout.objects.get(id=workout_id)
    client = User.objects.get(id=client_id)
    if workout.coach == request.user:
        workout.client.remove(client)
        workout.save()
    return redirect("workout:details_workout", workout_id)

workout/templates/workout/add.html
{% extends 'core/index.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" value="add_workout">Submit</button>
    </form>
{% endblock %}

workout/templates/workout/details.html
{% extends 'core/index.html' %}
{% block content %}

<div id="workout-details-cont">
    <div id="workout-details-info">
        <h1>{{workout.name}}</h1>
        <a href="{% url 'users:coach_info' workout.coach.id %}">
        <h2>{{workout.coach.first_name}} {{workout.coach.last_name}}</h2>
        </a>
        <p>participants: {{workout.client.count}}/{{workout.max_participants}} </p>
        <p>target: {{workout.target}} </p>
        <p>difficulty: {{workout.difficulty}} </p>
        <p>{{workout.day}} {{workout.start_time|date:"h:i a"}}-{{workout.end_time|date:"h:i a"}}</p>

        {%load workout_tags%}
        {% if request.user.is_authenticated%}
            {%get_workout_button request.user workout as button%}
            <a class="{{button.class}}" href="{{button.url}}">{{button.name}}</a>
        {%endif%}
    </div>

    <p id="workout-details-desc">{{workout.description}} </p>

    {% if request.user == workout.coach %}
    <div id="workout-participants">
        <h3>Participants</h3>
        {% for participant in workout.client.all%}
        <div class="participant-cont">
            <p>{{participant.first_name}} {{participant.last_name}}</p>
            <a href="{% url 'workout:remove_client'%}?workout_id={{workout.id}}&client_id={{participant.id}}">remove</a>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock %}

workout/templates/workout/schedule.html
{% extends 'core/index.html' %}
{% block content %}
<div id="schedule-container">
    <h1> schedule </h1>
    <div id="schedule-table">
        {% for day in weekdays %}
            <div class="schedule-row">
                <h2> {{ day.0 }}</h2>
                {% for workout in workouts %}
                    {% if workout.day == day.0 %}
                    <div class="schedule-workout">
                        <p>{{workout.start_time|date:"h:i a"}}</p>
                        <a href="{% url 'workout:details_workout' workout.id%}" ><p>{{ workout.name }}</p></a>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}