GymWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path('workout/', include("workout.urls")),
    path('memberships/', include("memberships.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path

from workout.urls import app_name
from . import views

app_name='core'

urlpatterns = [
    path('', views.home, name='home'),
]

memberships/urls.py
from django.urls import path
from . import views

app_name = 'memberships'

urlpatterns = [
    path("show/", views.show_memberships, name="show_memberships"),
    path("cancel_membership", views.cancel_membership, name="cancel_membership"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("my_profile/", views.current_profile, name="current_profile"),
    path("logout/", views.logout_user, name="logout"),
    path("add_visit/<int:user_id>/", views.add_visit, name="add_visit"),
    path("coaches/", views.show_coaches, name="coaches"),
    path("coaches/<int:coach_id>", views.coach_info, name="coach_info"), ## dodaj imie i nazwisko w linku
    path("edit/", views.edit_info, name="edit"),
]

workout/urls.py
from django.urls import path
from . import views

app_name = 'workout'

urlpatterns = [
    path('add/', views.add_workout, name='add_workout'),
    path('schedule/', views.schedule, name='schedule'),
    path('join/', views.join_workout, name='join_workout'),
    path('leave/', views.leave_workout, name='leave_workout'),
    path('delete/', views.delete_workout, name='delete_workout'),
    path('edit/', views.edit_workout, name='edit_workout'),
    path('details/<int:workout_id>', views.details_workout, name='details_workout'),
    path('remove_from_workout/',  views.remove_client_from_workout, name='remove_client'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'core/main.html')

core/templates/core/footer.html
<footer>
  <div>
    <p><strong>Opening hours:</strong></p>
      <ul>
          <li>Monday - Friday: 6:00 AM - 10:00 PM</li>
          <li>Saturday - Sunday: 8:00 AM - 8:00 PM</li>
      </ul>
  </div>
  <div>
    <p><strong>Contact:</strong></p>
    <p>Phone: <a href="tel:+48123456789">+48 123 456 789</a></p>
    <p>Email: <a href="mailto:info@silownia.pl">info@silownia.pl</a></p>
    <p>Address: Fitness Street 10, 00-123 City</p>
  </div>
  <div>
    <p><strong>Find us:</strong></p>
    <a href="https://facebook.com" target="_blank">Facebook</a> |
    <a href="https://instagram.com" target="_blank">Instagram</a>
  </div>
</footer>

core/templates/core/header.html
<header>
  <div id="logo-container" style="height: 100%">
    <a href="/">
      {% load static %}
      <img style="height: 100%" src="{% static 'logo.png' %}" alt="logo" >
    </a>
  </div>

  <div id="nav-container">
    <a href="{% url 'users:coaches' %}">coaches</a>
    <a href="{% url 'workout:schedule' %}">workouts</a>
    <a href="{% url 'memberships:show_memberships' %}">offer</a>
  </div>

  <div id="login-container">
    {% if user.is_authenticated %}
    <a href="{% url 'users:logout' %}">logout</a>
    <a href="{% url 'users:current_profile' %}">profile</a>
    {% else %}
    <a href="{% url 'users:login' %}">login</a>
    <a href="{% url 'users:register' %}">register</a>
    {% endif %}
  </div>
</header>

core/templates/core/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    {% include 'core/header.html' %}
    <main>
        {% block content %}
        {% endblock %}
    </main>
    {% include 'core/footer.html' %}
</body>
</html>

core/templates/core/main.html
{% extends 'core/index.html'%}
{% block content %}
{% load static %}

<div id="main-cont" class="animation">
    <h1>Welcome to 💪Gym</h1>
    <h2>Your journey to strength and health starts here!</h2>
    <h2>Why choose GymX?</h2>
    <h3>We offer state-of-the-art equipment, experienced trainers, and a wide range of classes to help you reach your fitness goals. Open 7 days a week!</h3>
    <h2>Take a Look Inside</h2>
    <div id="images">
        <img src="{% static 'gym1.jpg' %}" alt="State-of-the-art gym equipment">
        <img src="{% static 'gym2.jpg' %}" alt="Group fitness class">
        <img src="{% static 'gym3.jpg' %}" alt="Personal training session">
        <img src="{% static 'gym4.jpg' %}" alt="Personal training session">
        <img src="{% static 'gym5.jpg' %}" alt="Personal training session">
        <img src="{% static 'gym6.jpg' %}" alt="Personal training session">
        <img src="{% static 'gym7.jpg' %}" alt="Personal training session">
    </div>

</div>







{% endblock %}