GymWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path('workout/', include("workout.urls")),
    path('memberships/', include("memberships.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path

from workout.urls import app_name
from . import views

app_name='core'

urlpatterns = [
    path('', views.home, name='home'),
]

memberships/urls.py
from django.urls import path
from . import views

app_name = 'memberships'

urlpatterns = [
    path("show/", views.show_memberships, name="show_memberships"),
    path("cancel_membership", views.cancel_membership, name="cancel_membership"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("my_profile/", views.current_profile, name="current_profile"),
    path("logout/", views.logout_user, name="logout"),
    path("add_visit/<int:user_id>/", views.add_visit, name="add_visit"),
    path("coaches/", views.show_coaches, name="coaches"),
    path("coaches/<int:coach_id>", views.coach_info, name="coach_info"), ## dodaj imie i nazwisko w linku
    path("edit/", views.edit_info, name="edit"),
]

workout/urls.py
from django.urls import path
from . import views

app_name = 'workout'

urlpatterns = [
    path('add/', views.add_workout, name='add_workout'),
    path('schedule/', views.schedule, name='schedule'),
    path('join/', views.join_workout, name='join_workout'),
    path('leave/', views.leave_workout, name='leave_workout'),
    path('delete/', views.delete_workout, name='delete_workout'),
    path('edit/', views.edit_workout, name='edit_workout'),
    path('details/<int:workout_id>', views.details_workout, name='details_workout'),
    path('remove_from_workout/',  views.remove_client_from_workout, name='remove_client'),
]

memberships/models.py
from django.db import models
from users.models import User

class Payment(models.Model):
    date = models.DateField()
    client = models.ForeignKey(User, on_delete=models.CASCADE, related_name='payments')
    amount = models.FloatField()
    method = models.CharField(max_length=50, choices=[
        ('credit_card', 'Credit Card'),
        ('paypal', 'PayPal'),
        ('bank_transfer', 'Bank Transfer')
    ])
    status = models.CharField(
        max_length=20,
        choices=[
            ('pending', 'Pending'),
            ('completed', 'Completed'),
            ('cancelled', 'Cancelled'),
            ('scheduled', 'Scheduled'),
        ],
        default='pending'
    )

class Membership(models.Model):
    name = models.CharField(max_length=50)
    price_1 = models.FloatField()
    price_6 = models.FloatField()
    price_12 = models.FloatField()

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    is_coach = models.BooleanField()
    profile_picture = models.ImageField(upload_to='profile_pictures/',
                                        default='profile_pictures/default.png')
    gender = models.CharField(
        choices=[('M', 'Male'),
                 ('F', 'Female')],
        max_length=1)

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='client')
    membership = models.ForeignKey('memberships.Membership',
                                   on_delete=models.PROTECT,
                                   null=True)

class Coach(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='coach')
    hourly_rate = models.FloatField()
    description = models.TextField(null=True)
    phone_number = models.IntegerField(null=True)

class Visit(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    enter_time = models.TimeField()

users/forms.py
import os.path
from dataclasses import field

from PIL import Image
from django import forms
from django.conf import settings
from django.contrib.auth import validators
from django.contrib.auth.password_validation import validate_password
from django.forms import ModelForm, TextInput

from users.models import User, Client
from utils import delete_null_choice


class ClientRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(),
                               validators=[validate_password])
    username = forms.CharField(max_length=20,
                               validators=[validators.UnicodeUsernameValidator()],
                               error_messages={'unique': 'user with that username already exists'})
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password', 'gender']
        widgets = {
            'gender': forms.Select(attrs={'class': 'form-control'}),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.is_coach = False
        if commit:
            user.save()
            client = Client.objects.create(user=user)
            return client


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['gender'].choices = delete_null_choice(self.fields['gender'].choices)


class UserEditFrom(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'profile_picture']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.help_text = None

    def save(self, commit=True):
        user = super().save(commit=False)
        picture = self.cleaned_data['profile_picture']
        if picture:
            picture_new = Image.open(picture)
            width, height = picture_new.size
            min_param = min(width, height)
            left = (width - min_param) / 2
            right = width - left
            top = (height - min_param) / 2
            bottom = height - top
            picture_new = picture_new.crop((left, top, right, bottom))
            new_path = 'profile_pictures/user_' + str(user.id) + '.webp'
            picture_new.save(os.path.join(settings.MEDIA_ROOT, new_path), format='WEBP')
            user.profile_picture = new_path
        if commit:
            user.save()
        return user


class CoachEditForm(UserEditFrom):
    hourly_rate = forms.DecimalField(max_digits=5, decimal_places=2)
    description = forms.CharField(widget=forms.Textarea)
    phone_number = forms.CharField(widget=forms.TextInput)

memberships/views.py
from datetime import date
from dateutil.relativedelta import relativedelta
from django.shortcuts import render, redirect
from memberships.models import Membership, Payment


def show_memberships(request):
    memberships = Membership.objects.all()
    desc = {
        'basic': ['Unlimited gym access',
                  'Participation in one group workout',
                  'One complimentary personal training session']
    }
    desc['student'] = desc['basic'].copy() + ['Discounted pricing for students with valid ID']
    desc['premium'] = ['Unlimited gym access',
                       'Participation in group classes (full schedule)',
                       'Three complimentary personal training sessions',
                       'Access to sauna and spa facilities',]
    for membership in memberships:
        membership.desc = desc.get(membership.name)
        membership.prices = {
            int(field.name.split('_')[-1]): getattr(membership, field.name)
            for field in membership._meta.get_fields()
            if field.name.startswith('price_')
        }

    context = {
        'memberships': memberships,
        'payment_options': Payment._meta.get_field('method').choices,
    }

    if request.method == 'POST':
        user = request.user
        client = user.client
        membership_id = request.POST.get('membership_id')
        client.membership = memberships.get(pk=membership_id)
        client.save()
        payment_method = request.POST.get('method-' + membership_id)
        months, price = request.POST.get('option-' + membership_id).split(':')
        payments = [Payment.objects.create(
            date=date.today() + relativedelta(months=(month - 1)),
            client=request.user,
            amount=price,
            method=payment_method,
            status='completed' if month == 1 else 'scheduled',
        ) for month in range(1, int(months) + 1)]
        for payment in payments:
            payment.save()
        return redirect('users:current_profile')

    return render(request, 'memberships/memberships.html', context)

def cancel_membership(request):
    user = request.user
    user.client.membership = None
    user.client.save()
    for workout in user.client_workouts.all():
        workout.client.remove(user)
    for payment in Payment.objects.filter(client=user).filter(status='scheduled'):
        payment.status = 'cancelled'
        payment.save()
    return redirect('users:current_profile')

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from users.models import User, Visit
from django.contrib.auth import login, logout
from users.forms import ClientRegisterForm, UserEditFrom, CoachEditForm
from workout.models import Workout


def register(request):
    context = {
        'title' : 'Register'
    }
    form = ClientRegisterForm()
    if request.method == 'POST':
        form = ClientRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('memberships:show_memberships')
    context['form'] = form
    return render(request, 'users/form.html', context)

def login_user(request):
    context = {
        'title': 'Login'
    }
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return HttpResponseRedirect('/')

    context['form'] = form
    return render(request, 'users/form.html', context)

@login_required
def logout_user(request):
    user = request.user
    logout(request)
    return redirect("/")

@login_required
def current_profile(request):
    user = request.user
    context = {
        'user': user
    }
    if user.is_coach:
        workouts = Workout.objects.filter(coach=user).filter(status='active')
        context['workouts'] = workouts
        return render(request, 'users/coach_profile.html', context)
    else:
        workouts = Workout.objects.filter(client=user)
        context['workouts'] = workouts
        return render(request, 'users/user_profile.html', context)

from datetime import date, datetime
def add_visit(request, user_id):
    try:
        user = User.objects.get(pk=user_id)
        visit = Visit.objects.create(client=user, date=date.today(), enter_time=datetime.now().strftime("%H:%M:%S"))
        visit.save()
        return HttpResponse('ok')
    except User.DoesNotExist:
        return HttpResponse('no such user')

def show_coaches(request):
    coaches = User.objects.filter(is_coach=True)
    context = {
        'coaches': coaches,
    }
    return render(request, 'users/coaches.html', context)

def coach_info(request, coach_id):
    try:
        coach = User.objects.get(id=coach_id)
        workouts = Workout.objects.filter(coach=coach)
        context = {
            'coach': coach,
            "workouts": workouts,
        }
        return render(request, 'users/coach_page.html', context)
    except User.DoesNotExist:
        return HttpResponse('no such user')

@login_required
def edit_info(request):
    user = request.user
    context = {
        'title': 'Edit profile'
    }
    if user.is_coach:
        data = {
            'hourly_rate': user.coach.hourly_rate,
            'description': user.coach.description,
            'phone_number': user.coach.phone_number,
        }
        context['form'] = CoachEditForm(instance=request.user, initial=data)
        if request.method == 'POST':
            form = CoachEditForm(request.POST, request.FILES, instance=user, initial=data)
            form.save()
            for name, value in data.items():
                if form.cleaned_data[name] != value:
                    setattr(user.coach, name, form.cleaned_data[name])
            user.coach.save()
            return redirect('users:current_profile')
    else:
        context['form'] = UserEditFrom(instance=request.user)
        if request.method == 'POST':
            form = UserEditFrom(request.POST, request.FILES, instance=request.user)
            form.save()
            return redirect('users:current_profile')
    return render(request, 'users/form.html', context)

users/templates/users/coach_page.html
{% extends 'core/index.html' %}
{% block content %}
<div id="coach-page-cont">
    <img alt="profile_picture" src="{{coach.profile_picture.url}}">

    <div>
        <h1>{{coach.first_name}} {{coach.last_name}}</h1>
        <h1>{{coach.email}}</h1>
        <h1>{{coach.coach.phone_number}}</h1>
    </div>

    <p id="coach-page-desc">{{coach.coach.description}}</p>

    <div id="coach-page-workouts">
        <h2>Workouts</h2>
        {% for workout in workouts %}
        <h3>{{workout.name}}</h3>
        <a href="{% url 'workout:details_workout' workout.id%}" >details</a>
        {% endfor %}
    </div>
</div>


{% endblock %}

users/templates/users/coach_profile.html
{% extends 'core/index.html' %}
{% block content %}

<div id="profile-cont">
    {%include 'users/user_info.html'%}
    <div class="profile-info-cont" id="profile-info-cont-coach">
       <h2>my workouts:</h2>
        {% for workout in workouts %}
        <div class="workout-buttons">
            <a href="{% url 'workout:details_workout' workout.id%}" >{{workout.name}} <br></a>
            <a href="{% url 'workout:delete_workout'%}?workout_id={{workout.id}}">delete</a>
            <a href="{%url 'workout:edit_workout'%}?workout_id={{workout.id}}">edit</a>
        </div>
        {% endfor %}
        <a href="{% url 'workout:add_workout'%}">add</a>
    </div>
</div>
{% endblock %}

users/templates/users/coaches.html
{% extends 'core/index.html' %}
{% block content %}

<div id="coaches-page">
    <h1>Our Coaches</h1>
    <div id="all-coaches-containers">
        {% for coach in coaches %}
        <div class="coach-container">
            <div class="coach-paragraphs-cont">
                <p>{{coach.first_name}}</p>
                <p>{{coach.last_name}}</p>
                <p>{{coach.email}}</p>
                <a href="{%url 'users:coach_info' coach.id %}">More info</a>
            </div>
            <img alt="coach_profile_picture" src="{{coach.profile_picture.url}}">
            <p class="coaches-all-description">{{coach.coach.description}}</p>
        </div>
        {% endfor %}
    </div>

</div>


{% endblock %}

users/templates/users/form.html
{% extends 'core/index.html' %}
{% block content %}
<div class="form-container">
    <form method="post" class="form-horizontal" enctype="multipart/form-data">
        <h1>{{title}}</h1>
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="submit">
    </form>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'core/index.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="submit">
    </form>

{% endblock %}

users/templates/users/membership.html
{% extends 'core/index.html' %}
{% block content %}

<h1>memberships</h1>

{% for membership in memberships %}
<div>
    <p>{{membership.name}}</p>
    <p>{{membership.price}}</p>
    {% if user.is_authenticated %}
        {% if request.user.client.membership.id != membership.id %}
        <a>{% if request.user.client.membership is null%}get{% else %}change{%endif%}</a>
        {% endif %}
    {% endif %}
</div>
{% endfor %}

{% endblock %}

users/templates/users/memberships.html
{% extends 'core/index.html' %}
{% block content %}

<h1>memberships</h1>

{% for membership in memberships %}
<form>
    <p>{{membership.name}}</p>
    <p>{{membership.price_12}}</p>
    {% if user.is_authenticated %}

    {% if request.user.client.membership.id != membership.id %}
    <a href="{% url 'users:payment' membership_id=membership.id%}">{% if request.user.client.membership is null%}get{% else %}change{%endif%}</a>
    {% endif %}

    {% endif %}
</form>
{% endfor %}

{% endblock %}

users/templates/users/user_info.html
{% block user_info %}

<div id="user-info-cont">
    <img alt="profile_picture" src="{{ user.profile_picture.url }}" >
    <div id="user-info-par">
        <div>
            <h1>username: <br>{{ user.username }}</h1>
            <h1>name: <br>{{ user.first_name }} {{ user.last_name}}</h1>
            <h1>email: <br>{{ user.email }}</h1>
        </div>
        <a href="{% url 'users:edit' %}">edit</a>
    </div>

</div>


{%endblock%}

users/templates/users/user_profile.html
{% extends 'core/index.html' %}
{% block content %}

<div id="profile-cont">
    {%include 'users/user_info.html'%}
    <div id="profile-info">
        <div id="profile-workouts" class="profile-info-cont">
            <h2>my workouts:</h2>
            {% for workout in workouts %}
            <a href="{% url 'workout:details_workout' workout.id%}" >{{workout.name}}</a>
            <a href="{% url 'workout:leave_workout'%}?workout_id={{workout.id}}">leave</a>
            {% endfor %}
        </div>

        <div id="profile-membership" class="profile-info-cont">
            <h2>membership: </h2>
            {% if user.client.membership is not None %}
            <h3>{{user.client.membership.name}}</h3>
            <a href="{% url 'memberships:cancel_membership' %}" >cancel membership</a>
            {% else %}
            <p>no active membership</p>
            {% endif %}
        </div>
    </div>

</div>



{% endblock %}